-- Initial schema for RigYourGoal

PRAGMA foreign_keys = ON;

-- Goals table: each goal is a persistent entity with tree structure (fork via parent_goal_id)
CREATE TABLE IF NOT EXISTS goals (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    raw_input TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    parent_goal_id TEXT,
    fork_context TEXT,
    current_milestone_id TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (parent_goal_id) REFERENCES goals(id) ON DELETE SET NULL,
    FOREIGN KEY (current_milestone_id) REFERENCES milestones(id) ON DELETE SET NULL
);

-- Milestones table: git-like tree of milestones per goal
CREATE TABLE IF NOT EXISTS milestones (
    id TEXT PRIMARY KEY NOT NULL,
    goal_id TEXT NOT NULL,
    milestone_order INTEGER NOT NULL,
    parent_milestone_id TEXT,
    plan TEXT,
    plan_summary TEXT,
    skill_path TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    result_summary TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_milestone_id) REFERENCES milestones(id) ON DELETE SET NULL
);

-- Skills table: generated by Harness Agents, verified by SideCar
CREATE TABLE IF NOT EXISTS skills (
    id TEXT PRIMARY KEY NOT NULL,
    milestone_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    harness_skill_id TEXT,
    parameters_schema TEXT,
    test_report TEXT,
    status TEXT NOT NULL DEFAULT 'requested',
    source_code_ref TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE CASCADE
);

-- Messages table: conversation history per goal
CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY NOT NULL,
    goal_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
);

-- Agent logs table: append-only log of agent activity
CREATE TABLE IF NOT EXISTS agent_logs (
    id TEXT PRIMARY KEY NOT NULL,
    goal_id TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    phase TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_goals_status ON goals(status);
CREATE INDEX IF NOT EXISTS idx_goals_parent ON goals(parent_goal_id);
CREATE INDEX IF NOT EXISTS idx_milestones_goal ON milestones(goal_id);
CREATE INDEX IF NOT EXISTS idx_milestones_parent ON milestones(parent_milestone_id);
CREATE INDEX IF NOT EXISTS idx_skills_milestone ON skills(milestone_id);
CREATE INDEX IF NOT EXISTS idx_messages_goal_created ON messages(goal_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_logs_goal ON agent_logs(goal_id, created_at);
