-- Initial schema
-- WorkSpace and WorkNode model for workhub mod
-- Extends the existing goal/milestone model

PRAGMA foreign_keys = ON;

-- Goals table: each goal is a persistent entity with tree structure (fork via parent_goal_id)
CREATE TABLE IF NOT EXISTS goals (
    id TEXT PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    raw_input TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    parent_goal_id TEXT,
    fork_context TEXT,
    current_milestone_id TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (parent_goal_id) REFERENCES goals(id) ON DELETE SET NULL,
    FOREIGN KEY (current_milestone_id) REFERENCES milestones(id) ON DELETE SET NULL
);

-- Milestones table: git-like tree of milestones per goal
CREATE TABLE IF NOT EXISTS milestones (
    id TEXT PRIMARY KEY NOT NULL,
    goal_id TEXT NOT NULL,
    milestone_order INTEGER NOT NULL,
    parent_milestone_id TEXT,
    plan TEXT,
    plan_summary TEXT,
    skill_path TEXT,
    status TEXT NOT NULL DEFAULT 'planned',
    result_summary TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_milestone_id) REFERENCES milestones(id) ON DELETE SET NULL
);

-- Skills table: generated by Harness Agents, verified by SideCar
CREATE TABLE IF NOT EXISTS skills (
    id TEXT PRIMARY KEY NOT NULL,
    milestone_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    harness_skill_id TEXT,
    parameters_schema TEXT,
    test_report TEXT,
    status TEXT NOT NULL DEFAULT 'requested',
    source_code_ref TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE CASCADE
);

-- Agent logs table: append-only log of agent activity
CREATE TABLE IF NOT EXISTS agent_logs (
    id TEXT PRIMARY KEY NOT NULL,
    goal_id TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    phase TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
);

-- WorkSpaces table: extends goals with resource management
-- Each WorkSpace corresponds 1:1 with a Goal
CREATE TABLE IF NOT EXISTS workspaces (
    id TEXT PRIMARY KEY NOT NULL,
    goal_id TEXT NOT NULL UNIQUE,
    current_node_id TEXT,
    
    -- WorkSpace-level resources
    goal_md TEXT,                       -- GOAL.md content
    plan_md TEXT,                       -- PLAN.md content
    
    -- Metadata
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE,
    FOREIGN KEY (current_node_id) REFERENCES worknodes(id) ON DELETE SET NULL
);

-- WorkNodes table: extends milestones with resource management
-- Replaces milestones for workhub-managed goals
CREATE TABLE IF NOT EXISTS worknodes (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    parent_node_id TEXT,
    node_order INTEGER NOT NULL DEFAULT 0,
    
    -- Status: planned/running/completed/failed
    status TEXT NOT NULL DEFAULT 'planned',
    
    -- WorkNode-level resources
    bug_md TEXT,                        -- BUG.md content (JSON array of BugEntry)
    user_manual_md TEXT,                -- USER_MANUAL.md content
    conclusion_md TEXT,                 -- CONCLUSION.md content
    
    -- Link to milestone for skills association
    milestone_id TEXT,
    
    -- Metadata
    plan_summary TEXT,
    result_summary TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_node_id) REFERENCES worknodes(id) ON DELETE SET NULL,
    FOREIGN KEY (milestone_id) REFERENCES milestones(id) ON DELETE SET NULL
);

-- GeneratorTasks table: tracks HarnessAgent tasks
CREATE TABLE IF NOT EXISTS generator_tasks (
    id TEXT PRIMARY KEY NOT NULL,
    workspace_id TEXT NOT NULL,
    worknode_id TEXT,
    specification TEXT NOT NULL,        -- The spec sent to HarnessAgent
    status TEXT NOT NULL DEFAULT 'pending',  -- pending/running/completed/failed
    result TEXT,                        -- Result from HarnessAgent
    user_manual TEXT,                   -- USER_MANUAL.md from HarnessAgent
    skills_json TEXT,                   -- Skills JSON from HarnessAgent
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    
    FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
    FOREIGN KEY (worknode_id) REFERENCES worknodes(id) ON DELETE SET NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_goals_status ON goals(status);
CREATE INDEX IF NOT EXISTS idx_goals_parent ON goals(parent_goal_id);
CREATE INDEX IF NOT EXISTS idx_milestones_goal ON milestones(goal_id);
CREATE INDEX IF NOT EXISTS idx_milestones_parent ON milestones(parent_milestone_id);
CREATE INDEX IF NOT EXISTS idx_skills_milestone ON skills(milestone_id);
CREATE INDEX IF NOT EXISTS idx_agent_logs_goal ON agent_logs(goal_id, created_at);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_workspaces_goal ON workspaces(goal_id);
CREATE INDEX IF NOT EXISTS idx_workspaces_current_node ON workspaces(current_node_id);
CREATE INDEX IF NOT EXISTS idx_worknodes_workspace ON worknodes(workspace_id);
CREATE INDEX IF NOT EXISTS idx_worknodes_parent ON worknodes(parent_node_id);
CREATE INDEX IF NOT EXISTS idx_worknodes_status ON worknodes(status);
CREATE INDEX IF NOT EXISTS idx_worknodes_milestone ON worknodes(milestone_id);
CREATE INDEX IF NOT EXISTS idx_generator_tasks_workspace ON generator_tasks(workspace_id);
CREATE INDEX IF NOT EXISTS idx_generator_tasks_status ON generator_tasks(status);
